version: "3.2"

services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGODB_DATABASE: nestjs_graphql_tutorial
    container_name: nestjs_graphql_tutorial_monogo
    ports:
      - 27018:27017